name = "my-profile"
account_id = "fb71c4eceaf623ae1b19b8b37d7a38cf"
main = "server/app.ts"
compatibility_date = "2025-04-26"
compatibility_flags = ["nodejs_compat"]

[vars]
BETTER_AUTH_URL = "https://you-find.me"
OPENAI_API_URL = "https://api.siliconflow.cn/v1"
OPENAI_MODEL = "deepseek-ai/DeepSeek-V4-Flash"
RESEND_FROM = "pleasure@yiming1234.cn"
VITE_MAPBOX_TOKEN = "pk.eyJ1IjoicGxlYXN1cmUxMjM0IiwiYSI6ImNtazJ2MXFwZDBiaDUzY3M4aXhnNGRxaWwifQ.v_BxUgGMO-diXUrd_juyQw"

[secrets]
required = [
  "AM_I_OK_SECRET",
  "BETTER_AUTH_SECRET",
  "GITHUB_CLIENT_ID",
  "GITHUB_CLIENT_SECRET",
  "GOOGLE_CLIENT_ID",
  "GOOGLE_CLIENT_SECRET",
  "RESEND_API_KEY",
  "NOTION_TOKEN",
  "OPENAI_API_KEY",
]

[placement]
mode = "smart"

[assets]
directory = "./dist/client"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[[r2_buckets]]
binding = "BLOG_BUCKET"
bucket_name = "cherry-studio"
remote = true

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "806b06d49b6541caaf7c1a703eedd77b"
localConnectionString = "postgresql://pleasure1234:123456@localhost:5432/mydb"
