name = "my-profile"
account_id = "fb71c4eceaf623ae1b19b8b37d7a38cf"
main = "server/app.ts"
compatibility_date = "2026-03-12"
compatibility_flags = ["nodejs_compat"]

[vars]
BETTER_AUTH_URL = "https://you-find.me"
OPENAI_API_URL = "https://api.siliconflow.cn/v1"
OPENAI_MODEL = "deepseek-ai/DeepSeek-V4-Flash"
RESEND_FROM = "pleasure@yiming1234.cn"

[placement]
mode = "smart"

[assets]
directory = "./dist/client"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*", "/feed.xml", "/blog/*"]

[[r2_buckets]]
binding = "BLOG_BUCKET"
bucket_name = "cherry-studio"
remote = true

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "806b06d49b6541caaf7c1a703eedd77b"
localConnectionString = "postgresql://pleasure1234:123456@localhost:5432/mydb"

[[kv_namespaces]]
binding = "KV_NAMESPACE"
id = "181e49e1558c47efb58170a55395d973"

[observability]
[observability.logs]
enabled = true
invocation_logs = true
