/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoryRouteImport } from './routes/story'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CvRouteImport } from './routes/cv'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AmIOkRouteImport } from './routes/am-i-ok'
import { Route as PasswordRouteRouteImport } from './routes/password/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as PasswordResetRouteImport } from './routes/password/reset'
import { Route as PasswordForgetRouteImport } from './routes/password/forget'
import { Route as BlogSplatRouteImport } from './routes/blog/$'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'

const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AmIOkRoute = AmIOkRouteImport.update({
  id: '/am-i-ok',
  path: '/am-i-ok',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordRouteRoute = PasswordRouteRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetRoute = PasswordResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => PasswordRouteRoute,
} as any)
const PasswordForgetRoute = PasswordForgetRouteImport.update({
  id: '/forget',
  path: '/forget',
  getParentRoute: () => PasswordRouteRoute,
} as any)
const BlogSplatRoute = BlogSplatRouteImport.update({
  id: '/blog/$',
  path: '/blog/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/password': typeof PasswordRouteRouteWithChildren
  '/am-i-ok': typeof AmIOkRoute
  '/chat': typeof ChatRoute
  '/cv': typeof CvRoute
  '/gallery': typeof GalleryRoute
  '/story': typeof StoryRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/blog/$': typeof BlogSplatRoute
  '/password/forget': typeof PasswordForgetRoute
  '/password/reset': typeof PasswordResetRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/password': typeof PasswordRouteRouteWithChildren
  '/am-i-ok': typeof AmIOkRoute
  '/chat': typeof ChatRoute
  '/cv': typeof CvRoute
  '/gallery': typeof GalleryRoute
  '/story': typeof StoryRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/blog/$': typeof BlogSplatRoute
  '/password/forget': typeof PasswordForgetRoute
  '/password/reset': typeof PasswordResetRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/password': typeof PasswordRouteRouteWithChildren
  '/am-i-ok': typeof AmIOkRoute
  '/chat': typeof ChatRoute
  '/cv': typeof CvRoute
  '/gallery': typeof GalleryRoute
  '/story': typeof StoryRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/blog/$': typeof BlogSplatRoute
  '/password/forget': typeof PasswordForgetRoute
  '/password/reset': typeof PasswordResetRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/password'
    | '/am-i-ok'
    | '/chat'
    | '/cv'
    | '/gallery'
    | '/story'
    | '/login'
    | '/signup'
    | '/blog/$'
    | '/password/forget'
    | '/password/reset'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/password'
    | '/am-i-ok'
    | '/chat'
    | '/cv'
    | '/gallery'
    | '/story'
    | '/login'
    | '/signup'
    | '/blog/$'
    | '/password/forget'
    | '/password/reset'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/password'
    | '/am-i-ok'
    | '/chat'
    | '/cv'
    | '/gallery'
    | '/story'
    | '/_auth/login'
    | '/_auth/signup'
    | '/blog/$'
    | '/password/forget'
    | '/password/reset'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PasswordRouteRoute: typeof PasswordRouteRouteWithChildren
  AmIOkRoute: typeof AmIOkRoute
  ChatRoute: typeof ChatRoute
  CvRoute: typeof CvRoute
  GalleryRoute: typeof GalleryRoute
  StoryRoute: typeof StoryRoute
  BlogSplatRoute: typeof BlogSplatRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/am-i-ok': {
      id: '/am-i-ok'
      path: '/am-i-ok'
      fullPath: '/am-i-ok'
      preLoaderRoute: typeof AmIOkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password': {
      id: '/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof PasswordRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password/reset': {
      id: '/password/reset'
      path: '/reset'
      fullPath: '/password/reset'
      preLoaderRoute: typeof PasswordResetRouteImport
      parentRoute: typeof PasswordRouteRoute
    }
    '/password/forget': {
      id: '/password/forget'
      path: '/forget'
      fullPath: '/password/forget'
      preLoaderRoute: typeof PasswordForgetRouteImport
      parentRoute: typeof PasswordRouteRoute
    }
    '/blog/$': {
      id: '/blog/$'
      path: '/blog/$'
      fullPath: '/blog/$'
      preLoaderRoute: typeof BlogSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PasswordRouteRouteChildren {
  PasswordForgetRoute: typeof PasswordForgetRoute
  PasswordResetRoute: typeof PasswordResetRoute
}

const PasswordRouteRouteChildren: PasswordRouteRouteChildren = {
  PasswordForgetRoute: PasswordForgetRoute,
  PasswordResetRoute: PasswordResetRoute,
}

const PasswordRouteRouteWithChildren = PasswordRouteRoute._addFileChildren(
  PasswordRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PasswordRouteRoute: PasswordRouteRouteWithChildren,
  AmIOkRoute: AmIOkRoute,
  ChatRoute: ChatRoute,
  CvRoute: CvRoute,
  GalleryRoute: GalleryRoute,
  StoryRoute: StoryRoute,
  BlogSplatRoute: BlogSplatRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
