/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CvRouteImport } from './routes/cv'
import { Route as PasswordRouteRouteImport } from './routes/password/route'
import { Route as SocialRouteImport } from './routes/social'
import { Route as StoryRouteImport } from './routes/story'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as PasswordForgetRouteImport } from './routes/password/forget'
import { Route as PasswordResetRouteImport } from './routes/password/reset'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordRouteRoute = PasswordRouteRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const PasswordForgetRoute = PasswordForgetRouteImport.update({
  id: '/forget',
  path: '/forget',
  getParentRoute: () => PasswordRouteRoute,
} as any)
const PasswordResetRoute = PasswordResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => PasswordRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/password': typeof PasswordRouteRouteWithChildren
  '/chat': typeof ChatRoute
  '/cv': typeof CvRoute
  '/social': typeof SocialRoute
  '/story': typeof StoryRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/password/forget': typeof PasswordForgetRoute
  '/password/reset': typeof PasswordResetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/password': typeof PasswordRouteRouteWithChildren
  '/chat': typeof ChatRoute
  '/cv': typeof CvRoute
  '/social': typeof SocialRoute
  '/story': typeof StoryRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/password/forget': typeof PasswordForgetRoute
  '/password/reset': typeof PasswordResetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/password': typeof PasswordRouteRouteWithChildren
  '/chat': typeof ChatRoute
  '/cv': typeof CvRoute
  '/social': typeof SocialRoute
  '/story': typeof StoryRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/password/forget': typeof PasswordForgetRoute
  '/password/reset': typeof PasswordResetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/password'
    | '/chat'
    | '/cv'
    | '/social'
    | '/story'
    | '/login'
    | '/signup'
    | '/password/forget'
    | '/password/reset'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/password'
    | '/chat'
    | '/cv'
    | '/social'
    | '/story'
    | '/login'
    | '/signup'
    | '/password/forget'
    | '/password/reset'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/password'
    | '/chat'
    | '/cv'
    | '/social'
    | '/story'
    | '/_auth/login'
    | '/_auth/signup'
    | '/password/forget'
    | '/password/reset'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PasswordRouteRoute: typeof PasswordRouteRouteWithChildren
  ChatRoute: typeof ChatRoute
  CvRoute: typeof CvRoute
  SocialRoute: typeof SocialRoute
  StoryRoute: typeof StoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password': {
      id: '/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof PasswordRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/password/forget': {
      id: '/password/forget'
      path: '/forget'
      fullPath: '/password/forget'
      preLoaderRoute: typeof PasswordForgetRouteImport
      parentRoute: typeof PasswordRouteRoute
    }
    '/password/reset': {
      id: '/password/reset'
      path: '/reset'
      fullPath: '/password/reset'
      preLoaderRoute: typeof PasswordResetRouteImport
      parentRoute: typeof PasswordRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PasswordRouteRouteChildren {
  PasswordForgetRoute: typeof PasswordForgetRoute
  PasswordResetRoute: typeof PasswordResetRoute
}

const PasswordRouteRouteChildren: PasswordRouteRouteChildren = {
  PasswordForgetRoute: PasswordForgetRoute,
  PasswordResetRoute: PasswordResetRoute,
}

const PasswordRouteRouteWithChildren = PasswordRouteRoute._addFileChildren(
  PasswordRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PasswordRouteRoute: PasswordRouteRouteWithChildren,
  ChatRoute: ChatRoute,
  CvRoute: CvRoute,
  SocialRoute: SocialRoute,
  StoryRoute: StoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
